### ISSUE TITLE
Getting Cors issue while requesting the API. 

### ISSUE THREAD

**Issue by pavan2920** [Idirect-Tech/Breeze-JS-SDK#7]
Hi All, Can you help me with solving the below issue? 

I am using a React app to connect to the Breeze api am getting this error. How i can pass the headers can anyone help me with please. 

![image](https://user-images.githubusercontent.com/10346150/214850142-4ebf6d57-5afd-46de-ac29-51177ee5ae4e.png)

**Comment by ShrikantOneture** [comment]
> Hi All, Can you help me with solving the below issue?
> 
> I am using a React app to connect to the Breeze api am getting this error. How i can pass the headers can anyone help me with please.
> 
> ![image](https://user-images.githubusercontent.com/10346150/214850142-4ebf6d57-5afd-46de-ac29-51177ee5ae4e.png)

Dear [pavan2920](https://github.com/pavan2920)
Please follow https://linuxpip.org/fix-access-to-xmlhttprequest-has-been-blocked-cors-policy/ and check if it resolves your issue.
