### ISSUE TITLE
Unable to load the session

### ISSUE THREAD

**Issue by pavan2920** [Idirect-Tech/Breeze-JS-SDK#8]
Hi Team, 
I am trying to follow the document and load the session but getting the below error, can you please help. 

Error: Could not authenticate credentials. Please check token and keys

Values passed : 
appKey : String(Both endcoded and decoded) 
appSecret: string 
Session Id : number and string. 

But still same error getting. Can you please help me on the same. 

Regards, 
Pavan.

**Comment by ShrikantOneture** [comment]
Dear User Session id is numeric  string

**Comment by pavan2920** [comment]
@ShrikantOneture  I have used the Numeric value still its same. Can you help me with same. 

![image](https://user-images.githubusercontent.com/10346150/215071108-830b662b-1f5f-4052-ba21-f001bb7b19b5.png)
